# Starship configuration

format = """
$directory\
$git_branch\
$git_status\
$docker_context\
$line_break\
$character"""

[directory]
truncation_length = 3
truncate_to_repo = false
style = 'bold cyan'
format = '[$path]($style)[$read_only]($read_only_style) '
repo_root_style = 'bold cyan'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[directory.substitutions]
'~/src/github.com/' = ''

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = ""
conflicted = "[~${count}](bold red) "
ahead = "[â‡¡${count}](bold green) "
behind = "[â‡£${count}](bold red) "
diverged = "[â‡•â‡¡${ahead_count}â‡£${behind_count}](bold red) "
untracked = "[?${count}](blue) "
stashed = "[*${count}](cyan) "
modified = "[!${count}](yellow) "
staged = "[+${count}](green) "
renamed = "[Â»${count}](blue) "
deleted = "[âœ˜${count}](red) "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[aws]
disabled = true

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ğŸ³ "
style = "bold blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
