[tools]
"aqua:suzuki-shunsuke/ghalint" = "1.5.4"
"cargo:dotter" = "0.13.4"
"cargo:fresh-editor" = "0.1.52"
"cargo:himalaya" = "1.1.0"
"npm:@anthropic-ai/claude-code" = "2.1.12"
"npm:@github/copilot" = "0.0.384"
"npm:@google/gemini-cli" = "0.24.0"
"npm:@openai/codex" = "0.87.0"
"npm:difit" = "2.2.7"
"npm:vercel" = "50.4.5"
"npm:vibe-kanban" = "0.0.155"
"npm:@ast-grep/cli" = "0.40.5"
"npm:@bitwarden/cli" = "2025.12.1"
"npm:@antfu/ni" = "28.2.0"
"npm:@mermaid-js/mermaid-cli" = "11.12.0"
"pipx:semgrep" = "1.148.0"
# starship = "1.23.0"
aqua = "2.53.7"
aws-cli = "2.33.2"
bat = "0.25.0"
bun = "1.3.6"
colima = "0.9.1"
delta = "0.18.2"
deno = "2.6.5"
direnv = "2.37.1"
docker-cli = "28.3.2"
fd = "10.2.0"
fzf = "0.65.0"
ghq = "1.8.0"
github-cli = "2.85.0"
go = "1.25.6"
jq = "1.8.1"
lazygit = "0.53.0"
lefthook = "1.13.6"
lsd = "1.1.5"
neovim = "0.11.3"
node = "24.13.0"
pipx = "1.8.0"
pnpm = "10.28.0"
ripgrep = "14.1.1"
skate = "1.0.1"
starship = "1.23.0"
terraform = "1.14.3"
tinymist = "0.14.4"
tmux = "3.6a"
tree-sitter = "0.25.8"
uv = "0.9.26"
xh = "0.24.1"
yarn = "4.9.4"
yazi = "25.5.31"
zoxide = "0.9.8"
sd = "1.0.0"
stylua = "2.3.1"
rust = "1.92.0"
python = "3.14.2"
ollama = "0.13.3"
golangci-lint = "2.8.0"

[settings]
idiomatic_version_file_enable_tools = ["python"]
