[tools]
"aqua:suzuki-shunsuke/ghalint" = "1.5.5"
"cargo:dotter" = "0.13.4"
"cargo:fresh-editor" = "0.1.52"
"cargo:himalaya" = "1.1.0"
"npm:@anthropic-ai/claude-code" = "2.1.38"
"npm:@github/copilot" = "0.0.406"
"npm:@google/gemini-cli" = "0.27.3"
"npm:@openai/codex" = "latest"
"npm:difit" = "3.1.6"
"npm:vercel" = "50.13.2"
"npm:vibe-kanban" = "0.1.7"
"npm:@ast-grep/cli" = "0.40.5"
"npm:@bitwarden/cli" = "2026.1.0"
"npm:@antfu/ni" = "28.2.0"
"npm:@mermaid-js/mermaid-cli" = "11.12.0"
"npm:wrangler" = "latest"
"pipx:semgrep" = "1.151.0"
# starship = "1.23.0"
aqua = "2.53.7"
aws-cli = "2.33.18"
bat = "0.25.0"
bun = "1.3.9"
colima = "0.9.1"
delta = "0.18.2"
deno = "2.6.9"
direnv = "2.37.1"
docker-cli = "28.3.2"
fd = "10.2.0"
fzf = "0.65.0"
ghq = "1.8.0"
github-cli = "2.86.0"
go = "1.25.7"
jq = "1.8.1"
lazygit = "0.53.0"
lefthook = "2.1.0"
lsd = "1.1.5"
neovim = "0.11.3"
node = "24.13.0"
pipx = "1.8.0"
pnpm = "10.29.2"
ripgrep = "14.1.1"
skate = "1.0.1"
starship = "1.23.0"
terraform = "1.14.4"
tinymist = "0.14.4"
tmux = "3.6a"
tree-sitter = "0.25.8"
uv = "0.10.1"
xh = "0.24.1"
yarn = "4.9.4"
yazi = "25.5.31"
zoxide = "0.9.8"
sd = "1.0.0"
stylua = "2.3.1"
rust = "1.93.0"
python = "latest"
ollama = "0.13.3"
golangci-lint = "2.7.2"
ecspresso = "latest"
hyperfine = "latest"
lua = "5.4.0"
goreleaser = "latest"
mprocs = "latest"
aws = "latest"
act = "latest"
pre-commit = "latest"
flutter = "3.38.9"
ruby = "4.0.1"
"npm:@playwright/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
