[tools]
"aqua:suzuki-shunsuke/ghalint" = "latest"
"cargo:dotter" = "latest"
"cargo:fresh-editor" = "latest"
"cargo:himalaya" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:difit" = "latest"
"npm:vercel" = "latest"
"npm:vibe-kanban" = "latest"
"npm:@ast-grep/cli" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:wrangler" = "latest"
"pipx:semgrep" = "latest"
aqua = "latest"
aws-cli = "latest"
bat = "latest"
bun = "1.3.9"
colima = "latest"
delta = "latest"
deno = "2.6.9"
direnv = "latest"
docker-cli = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
go = "1.25.7"
jq = "latest"
lazygit = "latest"
lefthook = "latest"
lsd = "latest"
neovim = "latest"
node = "24.13.1"
pipx = "latest"
pnpm = "latest"
ripgrep = "latest"
skate = "latest"
starship = "latest"
terraform = "1.14.5"
tinymist = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
xh = "latest"
yarn = "latest"
yazi = "latest"
zoxide = "latest"
sd = "latest"
stylua = "latest"
rust = "1.93.1"
python = "latest"
ollama = "latest"
golangci-lint = "latest"
ecspresso = "latest"
hyperfine = "latest"
lua = "5.4.0"
goreleaser = "latest"
mprocs = "latest"
aws = "latest"
act = "latest"
pre-commit = "latest"
flutter = "3.38.9"
ruby = "4.0.1"
"npm:@playwright/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
